package com.gthr.gthrcollect.utils.constants

object FirebaseRealtimeDatabase {

    /*Collection Info Model*/
    const val COLLECTION_INFO_MODEL = "collectionInfoModel"

    /*Common*/
    const val USER_REF_KEY = "userRefKey"
    const val PROFILE_URL_KEY = "profileImageURL"
    const val DISPLAY_NAME="collectionDisplayName"
    const val RARITY = "rarity"
    const val NAME = "name"
    const val SET = "set"
    const val HIGHEST_BID_COST = "highestBidCost"
    const val HIGHEST_BID_ID = "highestBidID"
    const val LOWEST_ASK_COST = "lowestAskCost"
    const val LOWEST_ASK_ID = "lowestAskID"
    const val IMAGE_ID = "imageID"
    const val NUMBER_OF_FAVORITES = "numberOfFavorites"
    const val PRODUCT_TYPE = "productType"
    const val OBJECT_ID = "objectID"
    const val IMAGE_URL = "imageURL"
    const val TIER = "tier"
    const val CARD_TYPE = "cardType"

    /*CollectionInfoModel*/
    const val ABOUT = "about"
    const val BUY_LIST = "buyList"
    const val COLLECTION_DISPLAY_NAME = "collectionDisplayName"
    const val COLLECTION_RAW_NAME = "collectionRawName"
    const val FAVORITE_COLLECTION_LIST = "favoriteCollectionList"
    const val FAVORITE_PRODUCT_LIST = "favoriteProductList"
    const val FOLLOWERS_LIST = "followersList"
    const val SELL_LIST = "sellList"

    /*MTGModel*/
    const val ARTIST = "artist"
    const val ARTIST_IDS = "artist_ids"
    const val BOOSTER = "booster"
    const val BORDER_COLOR = "border_color"
    const val CARD_BACK_ID = "card_back_id"
    const val CMC = "cmc"
    const val COLLECTOR_NUMBER = "collector_number"
    const val COLOR_IDENTITY = "color_identity"
    const val COLORS = "colors"
    const val DIGITAL = "digital"
    const val FLAVOR_TEXT = "flavor_text"
    const val FOIL = "foil"
    const val FRAME = "frame"
    const val FULL_ART = "full_art"
    const val GAMES = "games"
    const val HIGHRES_IMAGE = "highres_image"
    const val ID = "id"
    const val ILLUSTRATION_ID = "illustration_id"
    const val IMAGE_URIS = "image_uris"
    const val KEYWORDS = "keywords"
    const val LANG = "lang"
    const val LARGE_IMG = "large_img"
    const val LAYOUT = "layout"
    const val LEGALITIES = "legalities"
    const val MANA_COST = "mana_cost"
    const val MTGO_FOIL_ID = "mtgo_foil_id"
    const val MTGO_ID = "mtgo_id"
    const val NONFOIL = "nonfoil"
    const val OBJECT = "object"
    const val ORACLE_ID = "oracle_id"
    const val ORACLE_TEXT = "oracle_text"
    const val OVER_SIZED = "oversized"
    const val PNG_IMG = "png_img"
    const val POWER = "power"
    const val PRICES = "prices"
    const val PRINTS_SEARCH_URI = "prints_search_uri"
    const val PRODUCED_MANA = "produced_mana"
    const val PROMO = "promo"
    const val PROMO_TYPES = "promo_types"
    const val RELEASED_AT = "released_at"
    const val REPRINT = "reprint"
    const val RESERVED = "reserved"
    const val RULINGS_URI = "rulings_uri"
    const val SCRYFALL_SET_URI = "scryfall_set_uri"
    const val SCRYFALL_URI = "scryfall_uri"
    const val SET_NAME = "set_name"
    const val SET_SEARCH_URI = "set_search_uri"
    const val SET_TYPE = "set_type"
    const val SET_URI = "set_uri"
    const val SMALL_IMG = "small_img"
    const val STORY_SPOTLIGHT = "story_spotlight"
    const val TCGPLAYER_ID = "tcgplayer_id"
    const val TEXTLESS = "textless"
    const val TOUGHNESS = "toughness"
    const val TYPE_LINE = "type_line"
    const val URI = "uri"
    const val VARIATION = "variation"
    const val WATERMARK = "watermark"
    const val ENGLISH = "English"
    const val JAPANESE = "Japanese"
    const val NUMBER = "number"

    /*PokemonModel*/
    const val HP = "hp"
    const val JAPANESE_NUMBER = "JapaneseNumber"
    const val JAPANESE_SET = "JapaneseSet"
    const val NO_LANGUAGE_NO_EDITION = "noLanguagenoEdition"
    const val PRICE_FOIL = "priceFoil"
    const val PRICE_NON_FOIL = "priceNonFoil"
    const val RESISTANCE = "resistance"
    const val RETREAT_COST = "retreatCost"
    const val STAGE = "stage"
    const val WEAKNESS = "weakness"

    /*FunkoModel*/
    const val CATEGORY = "category"
    const val EXCLUSIVITY = "exclusivity"
    const val FUNKO_TYPE = "funkoType"
    const val ITEM_NUMBER = "itemNumber"
    const val LICENSE = "license"
    const val MARKET_VALUE = "marketValue"
    const val RELEASE_DATE = "releaseDate"
    const val STATUS = "status"

    /*SealedModel*/
    const val CARD_TEXT = "cardText"
    const val MARKET_PRICE = "marketPrice"

    /*YugiohModel*/
    const val ASIAN_ENGLISH = "asianEnglish"
    const val ASIAN_ENGLISH_OG = "asianEnglishOG"
    const val DETAIL_PRICE = "detailPrice"
    const val ENGLISH_OG = "englishOG"
    const val EURO_ENGLISH = "euroEnglish"
    const val FIRST_DESCRIPTION = "firstDescription"
    const val FRENCH = "french"
    const val FRENCH_CANADIAN = "frenchCanadian"
    const val FRENCH_OG = "frenchOG"
    const val GERMAN = "german"
    const val GERMAN_OG = "germanOG"
    const val ITALIAN = "italian"
    const val ITALIAN_OG = "italianOG"
    const val KOREAN = "korean"
    const val KOREAN_OG = "koreanOG"
    const val OCEANIC_ENGLISH = "oceanicEnglish"
    const val PORTUGUESE = "portuguese"
    const val PORTUGUESE_OG = "portugueseOG"
    const val SPANISH = "spanish"
    const val SPANISH_OG = "spanishOG"
    const val STATS = "stats"


}