package com.gthr.gthrcollect.model.network.firebaserealtimedb

data class test(
    val askRefKey: String,
    val backImageURL: Any,
    val collectionRefId: Int,
    val collection_collectionDisplayName: String,
    val collection_collectionRawName: String,
    val collection_firebaseRef: String,
    val collection_id: Int,
    val collection_profileImageURL: String,
    val collection_userRefKey: String,
    val condition: Any,
    val createdAt: String,
    val creatorProfileURL: Any,
    val creatorUID: String,
    val edition: Any,
    val firebaseRef: String,
    val frontImageURL: Any,
    val id: Int,
    val itemObjectID: String,
    val itemRefKey: String,
    val language: Any,
    val price: Int,
    val productCategory: String,
    val productRefId: Int,
    val productType: String,
    val product_firImageURL: String,
    val product_firebaseRef: String,
    val product_group: String,
    val product_id: Int,
    val product_numberOfFavorites: Int,
    val product_prodObjectID: String,
    val product_productName: String,
    val product_productNumber: Int,
    val product_rarity: Any,
    val updatedAt: Any
)