package com.gthr.gthrcollect.model.domain


import kotlinx.serialization.Serializable

@Serializable
data class MTGDomainModel(
    val artist: String,
    val artistIds: String,
    val booster: String,
    val borderColor: String,
    val cardBackId: String,
    val cmc: Int,
    val collectorNumber: Int,
    val colorIdentity: String,
    val colors: String,
    val digital: String,
    val flavorText: String,
    val foil: String,
    val frame: Int,
    val fullArt: String,
    val games: String,
    val highestBidCost: Double,
    val highestBidID: String,
    val highresImage: String,
    val id: String,
    val illustrationId: String,
    val imageID: String,
    val imageUris: String,
    val keywords: String,
    val lang: String,
    val largeImg: String,
    val layout: String,
    val legalities: String,
    val lowestAskCost: Double,
    val lowestAskID: String,
    val manaCost: String,
    val mtgoFoilId: String,
    val mtgoId: String,
    val name: String,
    val nonfoil: String,
    val numberOfFavorites: Int,
    val objectID: String,
    val objectX: String,
    val oracleId: String,
    val oracleText: String,
    val oversized: String,
    val pngImg: String,
    val power: Int,
    val prices: String,
    val printsSearchUri: String,
    val producedMana: String,
    val productType: String,
    val promo: String,
    val promoTypes: String,
    val rarity: String,
    val releasedAt: String,
    val reprint: String,
    val reserved: String,
    val rulingsUri: String,
    val scryfallSetUri: String,
    val scryfallUri: String,
    val `set`: String,
    val setName: String,
    val setSearchUri: String,
    val setType: String,
    val setUri: String,
    val smallImg: String,
    val storySpotlight: String,
    val tcgplayerId: Int,
    val textless: String,
    val toughness: Int,
    val typeLine: String,
    val uri: String,
    val variation: String,
    val watermark: String
)